---
title: "Seletive depencies for AML cell lines in CCLE"
author: Fiorella Schischlik
date: December 9, 2019
output:
  md_document:
    variant: gfm
---

Load libraries.
```{r}
library(ggplot2)
library(ggrepel)
library(ComplexHeatmap)
library(ggpubr)
library(poolr)
library(reshape2)
```

Set directories.
```{r}
# dir_depmap <- "~/OneDrive - National Institutes of Health/DepMap/"
dir_depmap <- "~/datasets/depmap/"
dir_out <- "~/src/aml-2019/results/"
# on biowulf
#dir_depmap <- "/data/Lab_ruppin/projects/sl-nf1-cdkn2a/processed_data/"
#dir_out <- "/data/Lab_ruppin/schischlikf2/aml-2019/"
```

Load data.
```{r}

# load depmap data
depmap <- readRDS(paste(dir_depmap, "depmap_21Q3_screen_data.rds", sep=""))

# > str(depmap)
# List of 6
#  $ genes                          : chr [1:27184] "A1BG" "A1CF" "A2M" "A2ML1" ...
#  $ meta_data                      :'data.frame':        1787 obs. of  9 variables:
#   ..$ DepMap_ID: chr [1:1787] "ACH-000001" "ACH-000002" "ACH-000003" "ACH-000004" ...
#   ..$ samples  : chr [1:1787] "NIHOVCAR3_OVARY" "HL60_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE" "CACO2_LARGE_INTESTINE" "HEL_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE" ...
#   ..$ types    : chr [1:1787] "OVARY" "HAEMATOPOIETIC_AND_LYMPHOID_TISSUE" "LARGE_INTESTINE" "HAEMATOPOIETIC_AND_LYMPHOID_TISSUE" ...
#   ..$ cell_line: chr [1:1787] "NIHOVCAR3" "HL60" "CACO2" "HEL" ...
#   ..$ prim_met : chr [1:1787] "Metastasis" "Primary" "" "" ...
#   ..$ cancer   : chr [1:1787] "Ovarian Cancer" "Leukemia" "Colon/Colorectal Cancer" "Leukemia" ...
#   ..$ subtype  : chr [1:1787] "Adenocarcinoma, high grade serous" "Acute Myelogenous Leukemia (AML), M3 (Promyelocytic)" "Adenocarcinoma" "Acute Myelogenous Leukemia (AML), M6 (Erythroleukemia)" ...
#   ..$ age      : chr [1:1787] "60" "35" "" "30" ...
#   ..$ sex      : chr [1:1787] "Female" "Female" "Male" "Male" ...
#  $ mrna                           : num [1:27184, 1:1787] 3.1227 0.0566 0.251 0.111 NA ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : chr [1:27184] "A1BG" "A1CF" "A2M" "A2ML1" ...
#   .. ..$ : chr [1:1787] "ACH-000001" "ACH-000002" "ACH-000003" "ACH-000004" ...
#  $ scna                           : num [1:27184, 1:1787] -0.1117 0.1827 -0.0644 -0.0644 -0.0644 ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : chr [1:27184] "A1BG" "A1CF" "A2M" "A2ML1" ...
#   .. ..$ : chr [1:1787] "ACH-000001" "ACH-000002" "ACH-000003" "ACH-000004" ...
#  $ gene_fitness_crispr_depmap_21q3: num [1:27184, 1:1787] -0.1479 0.05463 0.00142 -0.01339 NA ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : chr [1:27184] "A1BG" "A1CF" "A2M" "A2ML1" ...
#   .. ..$ : chr [1:1787] "ACH-000001" "ACH-000002" "ACH-000003" "ACH-000004" ...
#  $ gene_fitness_rnai_depmap       : num [1:27184, 1:1787] 0.0367 0.0737 -0.1833 -0.1658 NA ...
#   ..- attr(*, "dimnames")=List of 2
#   .. ..$ : chr [1:27184] "A1BG" "A1CF" "A2M" "A2ML1" ...
#   .. ..$ : chr [1:1787] "ACH-000001" "ACH-000002" "ACH-000003" "ACH-000004" ...


```

Finding selective dependency.
```{r}

get_selective_dependency <- function(
  depmap=depmap,
  slot=slot){
  # Choose cell lines
  aml_cell_lines <- rownames(depmap$meta_data[grep("AML", depmap$meta_data$subtype),])
  non_aml_cl <- rownames(depmap$meta_data[which(!depmap$meta_data$cancer %in% c("Leukemia", "Lymphoma")), ])

  # Count number of cell lines available for each gene
  count_aml_cl <- rowSums(!is.na(depmap[[slot]][, aml_cell_lines]))
  count_non_aml_cl <- rowSums(!is.na(depmap[[slot]][, non_aml_cl]))

  # Genes with KO information for at least 5 cell lines in the aml and non aml
  # cell ines
  sel_genes <- (((count_aml_cl > 5) + (count_non_aml_cl >5)) == 2)

  # test using wilcox
  wilcoxon_dep <- apply(depmap[[slot]][sel_genes, ], 1, function(x)
    wilcox.test(x[aml_cell_lines], x[non_aml_cl] , alternative = 'less')$p.value)

  wilcox_df_summary <- data.frame(
    row.names = names(wilcoxon_dep), 
    count_aml_cl = count_aml_cl[sel_genes],
    count_non_aml_cl = count_non_aml_cl[sel_genes],
    wilcox_pval = wilcoxon_dep)

  wilcox_df_summary$BH <- p.adjust(wilcox_df_summary$wilcox_pval)
  
  return(wilcox_df_summary)
}


wilcox_crispr <- get_selective_dependency(depmap=depmap, slot="gene_fitness_crispr_depmap_21q3")
colnames(wilcox_crispr) <- c("count_aml_cl_crispr", "count_non_aml_cl_crispr", "wilcox_pval_cirspr", "BH_crispr")
wilcox_crispr$gene_name <- row.names(wilcox_crispr)

wilcox_rnai <- get_selective_dependency(depmap=depmap, slot="gene_fitness_rnai_depmap")
colnames(wilcox_rnai) <- c("count_aml_cl_rnai", "count_non_aml_cl_rnai", "wilcox_pval_rnai", "BH_rnai")
wilcox_rnai$gene_name <- row.names(wilcox_rnai)

wilcox_combined <- merge(wilcox_crispr, wilcox_rnai, by="gene_name", all=TRUE)

# Order by p-value
wilcox_combined <- wilcox_combined[order(wilcox_combined$wilcox_pval_cirspr), ]

write.csv(wilcox_combined, file=paste(dir_out, "selective_dependency_aml.tsv"))

```

Visualize dependency score for top X genes.
```{r}

# Functions
rank.array <- function(mat){
  mat.back = mat 
  mat = mat[!is.na(mat)]
  mat = rank(mat, ties.method = "average")/length(mat);
  mat.back[!is.na(mat.back)] = mat
  mat.back}

generate_plot_df <- function(
  screen=depmap,
  slot="gene_fitness_crispr_depmap_21q3",
  norm_rank=norm_rank,
  genes=c("CCND3"),
  aml_cell_lines,
  non_aml_cl){
  
  dependency_score <- reshape2::melt(t(screen[[slot]][genes, ]))
  colnames(dependency_score) <- c("cl_id", "gene_name", "dependency_score")
  norm_rank <- reshape2::melt(t(norm_rank[genes, ]))
  colnames(norm_rank) <- c("cl_id", "gene_name", "norm_rank")
  df_g <- cbind(dependency_score, norm_rank=norm_rank$norm_rank)
  # add grouping
  df_g$grouping <- "other_cell_line"
  df_g[df_g$cl_id %in% non_aml_cl, ]$grouping <- "non-AML_specific"
  df_g[df_g$cl_id %in% aml_cell_lines, ]$grouping <- "AML_specific"
  
  return(df_g)
}

# Plot
slot <- "gene_fitness_crispr_depmap_21q3"
#slot <- "gene_fitness_rnai_depmap"
# Rank normalized essentiality matrix
depmap_rank_norm <- apply(depmap[[slot]], 2, rank.array)

# Select genes
# selec <- row.names(wilcox_df_summary[which(wilcox_df_summary$BH < 0.00001),])
robust_sele_dep <- na.omit(wilcox_combined[wilcox_combined$BH_crispr < 0.1 & wilcox_combined$BH_rnai < 0.1, ])

aml_cell_lines <- rownames(depmap$meta_data[grep("AML", depmap$meta_data$subtype),])
non_aml_cl <- rownames(depmap$meta_data[which(!depmap$meta_data$cancer %in% c("Leukemia", "Lymphoma")), ])

# Generate dataframe for plotting
df_g <- generate_plot_df(
  screen=depmap,
  slot=slot,
  norm_rank=depmap_rank_norm,
  genes=robust_sele_dep$gene_name,
  aml_cell_lines=aml_cell_lines, 
  non_aml_cl=non_aml_cl)

# Give cell lines meaningful names
cl_name <- depmap$meta_data[c("DepMap_ID", "cell_line")]
df_gm <- merge(df_g, cl_name, by.x="cl_id", by.y="DepMap_ID")

saveRDS(df_gm, file=paste(dir_out, "df_gm.rds", sep=""))
df_gm <- readRDS(paste(dir_out, "df_gm.rds", sep=""))

# Plot
g <- ggplot(df_gm, aes(x=dependency_score, y=norm_rank, fill=grouping))
g <- g + geom_point(
  pch=21, colour="grey", fill="grey", size=1.7, alpha=0.5)
g <- g + geom_point(
  data=df_gm[df_gm$grouping=="AML_specific", ], 
  aes(x=dependency_score, y=norm_rank), 
  pch=21, colour="red", fill="red", size=1.7, alpha=0.5)
g <- g + geom_vline(xintercept= (-1), colour="red")
g <- g + geom_text_repel(
  data=na.omit(df_gm[df_gm$dependency_score < (-1) & df_gm$grouping=="AML_specific", ]), 
  aes(x=dependency_score, y=norm_rank, label=cell_line), color="blue", size=2, max.overlaps =50)
g <- g + facet_wrap(~ gene_name)
plot(g)

# Save plot
fn <- sprintf(paste(dir_out, "depmap_crispr_selective_dependency_comb_crispr_0p1_wilcox_all_gene_name.pdf", sep=""))
pdf(fn, height=8, width=12)
print(g)
dev.off()

# Annotate robust
wilcox_combined$robust_selective_dependency <- "no"
wilcox_combined[wilcox_combined$gene_name %in% robust_sele_dep$gene_name, ]$robust_selective_dependency <- "yes"

write.csv(wilcox_combined, file=paste(dir_out, "selective_dependency_aml_robust.tsv"))

```

Identify SL candidates for HOX genes
```{r}

# Resources: https://www.haematologica.org/article/view/9926
# As for the HOX question, we can divide leukemia (not just AML, but leukemia 
# – AML and ALL, so we have more) cell lines into HOX positive and HOX negative 
# to do the same figure as above. Here we can do a statistic between HOX 
# positive compared to HOX negative. To define HOX positive and negative,  The 
# list of HOX genes activated in AML cell lines are mostly of the HOXA cluster 
# (HOXA5, HOXA7, HOXA9, HOXA10, HOXA11) or the HOXB cluster (HOXB3, HOXB4, 
# HOXB5, HOXB6, HOXB7). So the HOX positive cell lines would be either HOXA 
# OR HOXB positive (both clubbed into the HOX positive group). Any cell line 
# that has neither HOXA nor HOXB expressed would be the HOX negative group.

HOXA <- c("HOXA1", "HOXA2", "HOXA3", "HOXA4", 
          "HOXA5", "HOXA6", "HOXA7", "HOXA9", 
          "HOXA10", "HOXA11", "HOXA13")
HOXB <- c("HOXB1", "HOXB2", "HOXB3", "HOXB4", 
          "HOXB5", "HOXB6", "HOXB7", "HOXB8",
          "HOXB9", "HOXB13")

HOX <- c(HOXA, HOXB, "MEIS1")

# AML
# check HOX gene distribution in aml_cell_lines, witout NA's
aml_cell_lines <- rownames(depmap$meta_data[grep("AML", depmap$meta_data$subtype),])
hox_expr <- depmap$mrna[HOX, aml_cell_lines]
colnames(hox_expr) <- depmap$meta_data[aml_cell_lines, ]$cell_line
hox_expr_naomit <- t(na.omit(t(hox_expr)))

# Plot 
Heatmap(
  t(scale(t(hox_expr_naomit))), 
  heatmap_legend_param = list(title = "Expression \n z-score"),
  cluster_rows = FALSE)

# ALL --------------------------------------------------------------------------
# check HOX gene distribution in aml_cell_lines, without NA's
all_cell_lines <- rownames(depmap$meta_data[grep("ALL", depmap$meta_data$subtype),])
hox_expr_all <- depmap$mrna[HOX, all_cell_lines]
colnames(hox_expr_all) <- depmap$meta_data[all_cell_lines, ]$cell_line
hox_expr_all_naomit <- t(na.omit(t(hox_expr_all)))

# Plot 
Heatmap(
  t(scale(t(hox_expr_all_naomit))), 
  heatmap_legend_param = list(title = "Expression \n z-score"),
  cluster_rows=FALSE)

# Plot AML and ALL together ----------------------------------------------------
# Plot PCA and kmeans
# Scale expression
hox <- cbind(hox_expr_all_naomit, hox_expr_naomit)

t(scale(t(hox)))
pca_on_hox <- prcomp(hox)
# 4 clusters
fit <- kmeans(pca_on_hox$rotation, 4)

# Annotation
ha <- HeatmapAnnotation(
  cell_line = c(rep("ALL", dim(hox_expr_all_naomit)[2]), rep("AML", dim(hox_expr_naomit)[2])),
  gp = gpar(col = "white"))

Heatmap(
  t(scale(t(hox))), 
  heatmap_legend_param = list(title = "Expression \n z-score"),
  top_annotation = ha, 
  cluster_rows = FALSE)

# create plot dataframe
to_plot <- as.data.frame(pca_on_hox$rotation[, c("PC1", "PC2")])
to_plot$cell_line <- c(rep("ALL", dim(hox_expr_all_naomit)[2]), 
                       rep("AML", dim(hox_expr_naomit)[2]))
to_plot$cluster <- fit$cluster
to_plot$cell_line <- row.names(to_plot)

p <- ggplot(data=to_plot, aes(x=PC1, y=PC2, fill=as.factor(cluster), label=cell_line, colour=as.factor(cluster)))
p <- p + geom_point(pch=21, alpha=0.8)
p <- p + geom_text_repel()
plot(p)

```

Identify HOX low and HOX high cell lines in AML.
```{r}

scaled_matrix <- t(scale(t(hox_expr_naomit)))
median_score <- median(colSums((scaled_matrix > 0) * 1))
lower_t <- quantile(colSums((scaled_matrix > 0) * 1), c(0:3/3))[2]

ha <- HeatmapAnnotation(
  hox = as.factor((colSums((scaled_matrix > 0) * 1) > lower_t) * 1),
  gp = gpar(col = "white"))

Heatmap(
  t(scale(t(hox_expr_naomit))), 
  heatmap_legend_param = list(title = "Expression \n z-score"),
  top_annotation = ha, 
  cluster_rows = FALSE)

```

Identify HOX low and HOX high cell lines in ALL
```{r}

scaled_matrix <- t(scale(t(hox_expr_all_naomit)))
median_score <- median(colSums((scaled_matrix > 0) * 1))
lower_t <- quantile(colSums((scaled_matrix > 0) * 1), c(0:3/3))[2]

ha <- HeatmapAnnotation(
  hox = as.factor((colSums((scaled_matrix > 0) * 1) > lower_t) * 1),
  gp = gpar(col = "white"))

Heatmap(
  t(scale(t(hox_expr_all_naomit))), 
  heatmap_legend_param = list(title = "Expression \n z-score"),
  top_annotation = ha, 
  cluster_rows = FALSE)

```

Essentiality function.
```{r}

essentiality <- function(
  screen=screen_data,
  sl_pair=sl_pair,
  data_slots=c("mrna", "scna"),
  gene_fitness_slots=c("crispr_depmap_21q3", "rnai_depmap"),
  q2=FALSE){
  
  # results columns
  results <- c()
  #results_column <- c("SL_A_B_", "SDL_A_B_", "SL_B_A_", "SR_B_A_")
  #results_column <- as.character(sapply(data_slots, function(x) paste(results_column, x, sep="")))
  #results_column <- append(c('GENE_A', 'GENE_B'), results_column)
  #names(results) <- results_column
  
  # Just in case make sure the sl_pair does not contain NA values
  if(sum(is.na(sl_pair)) == 0){
    
      if (q2){
        
        # q2 slots
        q2_slots <- paste0(data_slots, "_q2")
        
      for (score in gene_fitness_slots){
        
        for (slot in q2_slots){
          
          results[paste("GENE_A_", score, "_fit_score#cl")] <- sum((!is.na(screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_A"], ])) * 1)
        results[paste("GENE_B_", score, "_fit_score#cl")] <- sum((!is.na(screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_B"], ])) * 1)
  
          molecdata_q2 <- screen[[slot]][sl_pair["GENE_A"],]
          
          #print(molecdata_q2)
          
          results[paste("SL_A_B", slot, score, sep="_")] <- wilcox.test.na(
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_B"], molecdata_q2 == 0],
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_B"], molecdata_q2 > 0],
            alternative1 = "less")
          
          results[paste("SDL_A_B", slot, score, sep="_")] <- wilcox.test.na(
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_B"], molecdata_q2 < 2],
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_B"], molecdata_q2 == 2],
            alternative1 = "greater")
          
          # Change direction B -> A
          molecdata_q2 <- screen[[slot]][sl_pair["GENE_B"],]
          
          results[paste("SL_B_A", slot, score, sep="_")] <- wilcox.test.na(
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_A"], molecdata_q2 == 0],
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_A"], molecdata_q2 > 0],
            alternative1 = "less")
          
          results[paste("SR_B_A_", slot, score, sep="_")] <- wilcox.test.na(
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_A"], molecdata_q2 < 2],
            screen[[paste0("gene_fitness_",score)]][sl_pair["GENE_A"], molecdata_q2 == 2],
            alternative1 = "greater")
          }
        }
      }
  }
    return(results)
}



wilcox.test.na = function(x,y, alternative1, paired=FALSE) {
  
  tryCatch(
    wilcox.test(x, y, alternative=alternative1, paired=paired)$p.value,
    error = function(e) NA)
  
}

```

Run essentiality 
```{r}

run_essentiality <- function(data){
  
  expression <- depmap$mrna
  colnames(expression) <- depmap$meta_data$cell_line
  aml_cell_lines_symbol <- colnames(data)
  aml_matrix <- expression[, aml_cell_lines_symbol]
  HOX_status <- (colSums((scaled_matrix > 0) * 1) > lower_t) * 1
  aml_matrix <- rbind(HOX_status=c(HOX_status * 2), aml_matrix)

  essentiality_dep <- depmap$gene_fitness_crispr_depmap_21q3
  colnames(essentiality_dep) <- depmap$meta_data$cell_line
  aml_matrix_ess <- essentiality_dep[, aml_cell_lines_symbol]
  aml_matrix_ess <- rbind(HOX_status=c(HOX_status * 2), aml_matrix_ess)

  rnai <- depmap$gene_fitness_rnai_depmap
  colnames(rnai) <- depmap$meta_data$cell_line
  aml_matrix_rnai <- rnai[, aml_cell_lines_symbol]
  aml_matrix_rnai <- rbind(HOX_status=c(HOX_status * 2), aml_matrix_rnai)


  screen <- list(
    mrna_q2=aml_matrix,
    gene_fitness_crispr_depmap_21q3=aml_matrix_ess,
    gene_fitness_rnai_depmap=aml_matrix_rnai
  )

  gene_a <- "HOX_status"
  gene_names <- row.names(screen$mrna)
  
  essentiality_multiple <- as.data.frame(t(
    as.data.frame(
      sapply(gene_names, function(x) essentiality(
        screen=screen,
        sl_pair=c(GENE_A = gene_a, GENE_B = x),
        data_slots=c("mrna"),
        gene_fitness_slots=c("crispr_depmap_21q3", "rnai_depmap"),
        q2=TRUE)))))
  
  return(essentiality_multiple)
}

aml_essentiality <- run_essentiality(hox_expr_naomit)
all_essentiality <- run_essentiality(hox_expr_all_naomit)



```

Validation.
```{r}

essentiality_multiple <- data.frame(all_essentiality)
essentiality_multiple$SDL_BH_crispr <- p.adjust(essentiality_multiple$SDL_A_B_mrna_q2_crispr_depmap_21q3)
essentiality_multiple$SDL_BH_rnai <- p.adjust(essentiality_multiple$SDL_A_B_mrna_q2_rnai_depmap)
essentiality_multiple <- essentiality_multiple[order(essentiality_multiple$SDL_A_B_mrna_q2_crispr_depmap_21q3), ]

sdl <- data.frame(na.omit(essentiality_multiple[c(
  "SDL_A_B_mrna_q2_crispr_depmap_21q3", "SDL_BH_crispr",
  "SDL_A_B_mrna_q2_rnai_depmap", "SDL_BH_rnai")]))

# sdl$fisher <- apply(
#   sdl, 
#   1, 
#   function(x) { (poolr::fisher(x, adjust = "none"))$p})
# 
# sdl$BH <- p.adjust(sdl$fisher, method="BH")

```

Add drug targets.
```{r}

sdl$gene_name <- row.names(sdl)
drugs <- read.csv("~/OneDrive - National Institutes of Health/Druggability/Druggability.tsv", header=TRUE, sep="\t")

annotate.drugs.drugbank <- function(gene_name, drug.list=drugs){
  #print(gene_name)
  #print(gene_name)
  #print(head(drug.list))
  drug_gene <- drug.list[drug.list$gene_name==as.character(gene_name),]
  if(!(is.data.frame(drug_gene) && nrow(drug_gene)==0)){
    matched.drugs <- paste(unique(drug_gene$drug_name), collapse=",")
  }
  else{
    matched.drugs <- ""
  }
  #print(matched.drugs)
  return(matched.drugs)
}

sdl$drugbank <- sapply(sdl$gene_name, FUN=function(x) annotate.drugs.drugbank(x, drug.list=drugs))

write.csv(sdl, file=paste(dir_out, "HOX_dependency_ALL.tsv"))

# only subselect genes with drug targets
sdl_sub <-sdl[sdl$drugbank!="", ]
sdl_sub$BH_sub <- p.adjust(sdl_sub$SDL_A_B_mrna_q2_crispr_depmap_21q3, method="BH")

```

Plot AML.
```{r}

get_data_in_format <- function(
  depmap, 
  data, 
  scaled_matrix,
  aml_cell_lines_symbol=colnames(hox_expr_naomit)){
  
  expression <- depmap$mrna
  colnames(expression) <- depmap$meta_data$cell_line
  aml_cell_lines_symbol <- colnames(data)
  aml_matrix <- expression[, aml_cell_lines_symbol]
  HOX_status <- (colSums((scaled_matrix > 0) * 1) > lower_t) * 1
  aml_matrix <- rbind(HOX_status=c(HOX_status * 2), aml_matrix)

  essentiality_dep <- depmap$gene_fitness_crispr_depmap_21q3
  colnames(essentiality_dep) <- depmap$meta_data$cell_line
  aml_matrix_ess <- essentiality_dep[, aml_cell_lines_symbol]
  aml_matrix_ess <- rbind(HOX_status=c(HOX_status * 2), aml_matrix_ess)

  rnai <- depmap$gene_fitness_rnai_depmap
  colnames(rnai) <- depmap$meta_data$cell_line
  aml_matrix_rnai <- rnai[, aml_cell_lines_symbol]
  aml_matrix_rnai <- rbind(HOX_status=c(HOX_status * 2), aml_matrix_rnai)


  screen <- list(
    mrna_q2=aml_matrix,
    gene_fitness_crispr_depmap_21q3=aml_matrix_ess,
    gene_fitness_rnai_depmap=aml_matrix_rnai
  )

  gene_a <- "HOX_status"
  gene_names <- row.names(screen$mrna)
  return(screen)
}

screen <- get_data_in_format(
  depmap, 
  data=hox_expr_all_naomit, 
  scaled_matrix=scaled_matrix,
  aml_cell_lines_symbol=colnames(hox_expr_all_naomit))

# Visualize the gene essentiality data -----------------------------------------
#gof <- row.names(head(essentiality_multiple, 10))
sdl <- sdl[order(sdl$SDL_A_B_mrna_q2_crispr_depmap_21q3), ]
gof <- c("KMT2A", "DOT1L", "MEN1")
gof <- row.names(head(sdl, 10))
expression <- screen$mrna_q2["HOX_status", ]
gene_fitness_score <- screen$gene_fitness_crispr_depmap_21q3[gof, ]
#gene_fitness_score <- screen$gene_fitness_rnai_depmap[gof, ]
gfs_melted <- reshape2::melt(t(gene_fitness_score))
colnames(gfs_melted) <- c("cell_line", "gene_name", "gene_fitness_score")

gfs_melted$strata <- rep(expression, length(unique(gfs_melted$gene_name)))

gfs_melted$strata_name <- "HOX pos"
gfs_melted[gfs_melted$strata==0, ]$strata_name <- "HOX neg"

#gene_ess_plot <- data.frame(
#  expression = expression,
#  gene_fitness_score=gene_fitness_score,
#  strata=expression)

# Boxplots
my_comparisons <- list(c("HOX pos", "HOX neg"))

p <- ggboxplot(gfs_melted, x = "strata_name", y = "gene_fitness_score",
               color = "strata_name", palette =c("#00AFBB", "#E7B800"),
               add = "jitter", shape = "strata_name")
p <- p + ylim(c(-1.5, 0.8))
p <- p + stat_compare_means(
  comparisons = my_comparisons, 
  method = "wilcox.test",
  paired = FALSE)
p <- p + facet_wrap(~gene_name)
plot(p)

# single gene
expression <- screen$mrna_q2["HOX_status", ]
gene_fitness_score <- screen$gene_fitness_crispr_depmap_21q3["SYNE3", ]
#gene_fitness_score <- screen$gene_fitness_rnai_depmap["POLE2", ]

gene_ess_plot <- data.frame(
  expression = expression,
  gene_fitness_score=gene_fitness_score,
  strata=expression)

# Boxplots
my_comparisons <- list( c("0", "2") )

p <- ggboxplot(gene_ess_plot, x = "strata", y = "gene_fitness_score",
               color = "strata", palette =c("#00AFBB", "#E7B800"),
               add = "jitter", shape = "strata")
p <- p + stat_compare_means(
  comparisons = my_comparisons, 
  method = "wilcox.test",
  paired = FALSE)
plot(p)


```


