---
title: "List of prognostic genes from TCGA/TARGET."
author: Fiorella Schischlik
date: December 9, 2019
output:
  md_document:
    variant: gfm
---

Load libraries.
```{r}
library(biomaRt)
library(survival)
library(RegParallel)
library(survminer)
library(matrixStats)
library(ggplot2)
library(ggrepel)
require(statar) # for xtile
```

Set directories.
```{r}
dir.output <- "~/datasets/SLpediatric/sl_pairs_results/"
dir.figures <- "~/Google Drive/NIH_NCI/Projects/AML_pediatric/figures/"
dir.code <- "~/datasets/SLpediatric/R/"
dir.repo <- "~/src/SLpediatric/R/"
dir.rdata <- "~/datasets/SLpediatric/Rdata_object/version6_nbl1-3/"
dir.ppi <- "~/datasets/STRING/"
dir.depmap <- "~/datasets/DepMap/"
dir.aml <- "~/datasets/SLpediatric/Rdata_object/version7_aml/"
dir.target <- "/Users/schischlikf2/datasets/SLpediatric/datasets/TARGET/"
```

Functions for subsetting prob Rdata objects.
```{r}

subset.prob.tcga <- function(prob, ix){
  
  prob$samples <- prob$samples[ix]
  prob$types <- prob$types[ix]
  prob$mRNA <- prob$mRNA[,ix]
  prob$scna <- prob$scna[,ix]
  prob$mRNAq <- prob$mRNAq[,ix]
  prob$scnaq <- prob$scnaq[,ix]
  prob$mRNAq2 <- prob$mRNAq2[,ix]
  prob$scnaq2 <- prob$scnaq2[,ix]
  prob$sex <- prob$sex[ix]
  prob$age <- prob$age[ix]
  prob$race <- prob$race[ix]
  prob$survival <- prob$survival[ix,]
  prob$stage <- prob$stage[ix]
  prob$mRNA.norm <- prob$mRNA.norm[,ix]
  prob$scna.norm <- prob$scna.norm[,ix]
  prob$surv.dt <- prob$surv.dt[ix,]
  
  return(prob)
}

subset.genes.prob.tcga <- function(prob, ix){
  
  prob$genes <- prob$genes[ix]
  prob$entrez <- prob$entrez[ix]
  prob$samples <- prob$samples
  prob$types <- prob$types
  prob$mRNA <- prob$mRNA[ix, ]
  prob$scna <- prob$scna[ix, ]
  prob$mRNAq <- prob$mRNAq[ix, ]
  prob$scnaq <- prob$scnaq[ix, ]
  prob$mRNAq2 <- prob$mRNAq2[ix, ]
  prob$scnaq2 <- prob$scnaq2[ix, ]
  prob$sex <- prob$sex
  prob$age <- prob$age
  prob$race <- prob$race
  prob$survival <- prob$survival
  prob$stage <- prob$stage
  prob$mRNA.norm <- prob$mRNA.norm[ix, ]
  prob$scna.norm <- prob$scna.norm[ix, ]
  prob$surv.dt <- prob$surv.dt
  
  return(prob)
}

subset.genes.prob.target <- function(prob, ix){
  prob$genes <- prob$genes[ix]
  prob$ensembl <- prob$ensembl[ix]
  prob$ensembl_version <- prob$ensembl_version[ix]
  prob$scna <- prob$scna[ix, ]
  prob$mRNA <- prob$mRNA[ix, ]
  prob$samples <- prob$samples
  prob$types <- prob$types
  prob$mutations <- prob$mutations
  prob$sex <- prob$sex
  prob$age <- prob$age
  prob$race <- prob$race
  prob$ethnicity <- prob$ethnicity
  prob$survival <- prob$survival
  prob$eventfree <- prob$eventfree
  
  return(prob) 
}

```

Cox function.
```{r}
cox.gene.expression <- function(gene, surv_mat=surv_mat){
  
  cox_uncntrl <- coxph(Surv(time, status) ~ gene, data=surv_mat)
  summary_uncntrl  <- summary(cox_uncntrl)
    
  cox_cntrl <- coxph(Surv(time, status) ~ gene + age + strata(sex, race), data=surv_mat)
  summary_cntrl  <- summary(cox_cntrl)
    
  res <- c(summary_uncntrl$coefficients["gene", 1:5], summary_cntrl$coefficients["gene", 1:5])
  
  return(res)
}

```


Load data.
```{r}
# load depmap data
load(paste(dir.depmap, "depmap_19Q3.RData", sep=""))
# load TCGA data
load(paste(dir.code, "prob.TCGA.extended.qnorm.RData", sep=""));prob0=prob
rm(prob)
# load TARGET data
load(paste(dir.aml, "aml.fpkms.n145.hg38.prob.Rdata", sep="")) # prob_name=aml.fpkms.prob.hg38

```

Preprocess TCGA data.
```{r}
# select LAML only
ix <- which(prob0$types=="LAML")
prob_adult_aml <- subset.prob.tcga(prob0, ix)

# free up some memory
rm(prob0)

# select only protein coding genes
ensembl <- useMart(
  "ensembl", 
  dataset="hsapiens_gene_ensembl")

gene_biotype <- getBM(
  attributes = c('hgnc_symbol', 'gene_biotype'), 
  filters = 'hgnc_symbol', 
  values = prob_adult_aml$genes, 
  mart = ensembl)

# index of all protein coding genes
all_protein_coding <- gene_biotype[gene_biotype$gene_biotype=="protein_coding", ]$hgnc_symbol
ix <- which(prob_adult_aml$genes %in% all_protein_coding)

# subset matrix
aml_intermediate <- subset.genes.prob.tcga(prob_adult_aml, ix)

# only select genes with a median FPKM >1
ix <- which(rowMedians(aml_intermediate$mRNA) > 10)
aml_tcga <- subset.genes.prob.tcga(aml_intermediate, ix)

# assign column and rownames to mRNA
colnames(aml_tcga$mRNA) <- aml_tcga$samples
row.names(aml_tcga$mRNA) <- aml_tcga$genes

```

Preprocess TARGET data.
```{r}
# only select protein coding genes
aml.fpkms.prob.hg38$ensembl_version <- aml.fpkms.prob.hg38$ensembl
aml.fpkms.prob.hg38$ensembl <- sapply(
  aml.fpkms.prob.hg38$ensembl_version, 
  function(x) strsplit(as.character(x), split="\\.")[[1]][1])
row.names(aml.fpkms.prob.hg38$mRNA) <- aml.fpkms.prob.hg38$ensembl

ensembl <- useMart(
  "ensembl", 
  dataset="hsapiens_gene_ensembl")

gene_biotype <- getBM(
  attributes = c('ensembl_gene_id', 'gene_biotype'), 
  filters = 'ensembl_gene_id', 
  values = aml.fpkms.prob.hg38$ensembl, 
  mart = ensembl)

# index of all protein coding genes
all_protein_coding <- gene_biotype[gene_biotype$gene_biotype=="protein_coding", ]$ensembl_gene_id
ix <- which(aml.fpkms.prob.hg38$ensembl %in% all_protein_coding)

# subset matrix
pediatric_aml_intermediate <- subset.genes.prob.target(aml.fpkms.prob.hg38, ix)

# only select genes with a median FPKM >1
ix <- which(rowMedians(pediatric_aml_intermediate$mRNA) > 1)
pediatric_aml <- subset.genes.prob.target(pediatric_aml_intermediate, ix)

# change codex for survival (death=1, alive=0), needed for cox regression
pediatric_aml$surv.data <-  data.frame(time=pediatric_aml$survival[,1], 
           status=ifelse(pediatric_aml$survival[,2]==0,1,0))

```

Prognostic genes from TCGA/TARGET.
```{r}
#### TCGA ----------------------------------------------------------------------

# create dataframe
surv_mat <- data.frame(
  samples=aml_tcga$samples,
  sex=aml_tcga$sex,
  age=aml_tcga$age,
  race=aml_tcga$race,
  stage=aml_tcga$stage,
  time=aml_tcga$surv.dt$time,
  status=aml_tcga$surv.dt$status)

# merge and transform data
# take log2 of FPKM values
cox_data <- cbind(surv_mat, t(log2(aml_tcga$mRNA + 1)))
scaled_data <- cbind(surv_mat, scale(t(log2(aml_tcga$mRNA + 1))))

# Run Cox Surv(time, status) ~ [*] + age + strata(sex, race)
cox_mrna <- t(apply(t(log2(aml_tcga$mRNA + 1)), 2, function(gene) cox.gene.expression(gene, surv_mat)))
colnames(cox_mrna) <- c("uncntrl_coef", "uncntrl_HR", "uncntrl_se_coeff", "uncntrl_z", "uncntrl_P",
                        "cntrl_coef", "cntrl_HR", "cntrl_se_coeff", "cntrl_z", "cntrl_P")

cox_mrna <- as.data.frame(cox_mrna)
cox_mrna$cntrl_padjust <- p.adjust(cox_mrna$cntrl_P, method="BH")
cox_mrna$uncntrl_padjust <- p.adjust(cox_mrna$uncntrl_P, method="BH")
cox_mrna$hgnc_symbol <- row.names(cox_mrna)

# Plot Hazard ratio vs P value
p <- ggplot(data=cox_mrna, aes(x=log2(cntrl_HR), y=-log10(cntrl_P)))
p <- p + geom_point(fill="blue", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_point(data=cox_mrna[cox_mrna$cntrl_padjust < 0.05, ], 
                    aes(x=log2(cntrl_HR), y=-log10(cntrl_P)),
                    fill="red", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_text_repel(data=cox_mrna[cox_mrna$cntrl_padjust < 0.05 & log2(cox_mrna$cntrl_HR) > 0 , ], 
                         aes(x=log2(cntrl_HR), y=-log10(cntrl_P), label=hgnc_symbol), 
                         color="red")
p <- p + geom_text_repel(data=cox_mrna[cox_mrna$cntrl_padjust < 0.05 & log2(cox_mrna$cntrl_HR) < 0 , ], 
                         aes(x=log2(cntrl_HR), y=-log10(cntrl_P), label=hgnc_symbol), 
                         color="blue")
p <- p + coord_fixed(ratio = 1)
p <- p + theme_bw()
p <- p + theme(axis.text.x=element_text(colour="black", size=10), 
               axis.text.y=element_text(colour="black", size=10))
print(p)

fn <- sprintf(paste(dir.figures, "cox_tcga_cntrl_fdr0p5.pdf", sep=""))
pdf(fn, height=6, width=6)
print(p)
dev.off()

# Plot Hazard ratio vs P value 
# for uncntrl
p <- ggplot(data=cox_mrna, aes(x=log2(uncntrl_HR), y=-log10(uncntrl_P)))
p <- p + geom_point(fill="blue", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_point(data=cox_mrna[cox_mrna$uncntrl_padjust < 0.01, ], 
                    aes(x=log2(uncntrl_HR), y=-log10(uncntrl_P)),
                    fill="red", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_text_repel(data=cox_mrna[cox_mrna$uncntrl_padjust < 0.01 & log2(cox_mrna$uncntrl_HR) > 0 , ], 
                         aes(x=log2(uncntrl_HR), y=-log10(uncntrl_P), label=hgnc_symbol), 
                         color="red")
p <- p + geom_text_repel(data=cox_mrna[cox_mrna$uncntrl_padjust < 0.01 & log2(cox_mrna$uncntrl_HR) < 0 , ], 
                         aes(x=log2(uncntrl_HR), y=-log10(uncntrl_P), label=hgnc_symbol), 
                         color="blue")
p <- p + coord_fixed(ratio = 1)
p <- p + theme_bw()
p <- p + theme(axis.text.x=element_text(colour="black", size=10), 
               axis.text.y=element_text(colour="black", size=10))
print(p)

fn <- sprintf(paste(dir.figures, "cox_tcga_uncntrl_fdr0p1.pdf", sep=""))
pdf(fn, height=8, width=8)
print(p)
dev.off()


#### TARGET --------------------------------------------------------------------

surv_mat <- data.frame(
  samples=pediatric_aml$samples,
  sex=pediatric_aml$sex,
  age=pediatric_aml$age,
  race=pediatric_aml$race,
  ethnicity=pediatric_aml$ethnicity,
  tissue=pediatric_aml$tissue,
  time=pediatric_aml$surv.data$time,
  status=pediatric_aml$surv.data$status)

# merge and transform data
# take log2 of FPKM values
cox_data <- cbind(surv_mat, t(log2(pediatric_aml$mRNA + 1)))
scaled_data <- cbind(surv_mat, scale(t(log2(pediatric_aml$mRNA + 1 ))))

# Run Cox in parallel
res <- RegParallel(
  data = cox_data,
  formula = 'Surv(time, status) ~ [*] + age + strata(sex, race, ethnicity, tissue)',
  FUN = function(formula, data)
    coxph(formula = formula,
          data = data,
          ties = 'efron'),
  FUNtype = 'coxph',
  variables = colnames(cox_data)[9:ncol(cox_data)],
  blocksize = 1000,
  cores = 2,
  nestedParallel = FALSE,
  conflevel = 95,
  p.adjust = "BH")

# Annotate results
res_noAge <- res[res$Term!="age", ]
gene_hgnc<- getBM(
  attributes = c('ensembl_gene_id', 'hgnc_symbol'), 
  filters = 'ensembl_gene_id', 
  values = res_noAge$Variable, 
  mart = ensembl)

# Merge annotation
m.res <- merge(res_noAge, gene_hgnc, by.x="Variable", by.y="ensembl_gene_id", all.x = TRUE)

# Plot results
m.res[order(m.res$P, decreasing=FALSE), ]

# Plot Hazard ratio vs P value
p <- ggplot(data=m.res, aes(x=log2(HR), y=-log10(P)))
p <- p + geom_point(fill="blue", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_point(data=m.res[m.res$P.adjust < 0.05, ], 
                    aes(x=log2(HR), y=-log10(P)),
                    fill="red", colour="white", pch=21, alpha=0.5, size=2.5)
p <- p + geom_text_repel(data=m.res[m.res$P.adjust < 0.05 & log2(m.res$HR) > 0 , ], 
                         aes(x=log2(HR), y=-log10(P), label=hgnc_symbol), 
                         color="red")
p <- p + geom_text_repel(data=m.res[m.res$P.adjust < 0.05 & log2(m.res$HR) < 0 , ], 
                         aes(x=log2(HR), y=-log10(P), label=hgnc_symbol), 
                         color="blue")
p <- p + coord_fixed(ratio = 1)
p <- p + theme_bw()
p <- p + theme(axis.text.x=element_text(colour="black", size=10), 
               axis.text.y=element_text(colour="black", size=10))
print(p)

fn <- sprintf(paste(dir.figures, "cox_covar_age.sex.race.ethnicity.pdf", sep=""))
pdf(fn, height=6, width=6)
print(p)
dev.off()

 
```

Plot survival (Kaplan Maier plots).
```{r}
# try example with one gene

km.gene.obj <- function(cox_data, scaled_data=scaled_data, gene=gene, gene_symbol=gene_symbol){
  cox.g1 <- cox_data[, c("samples", "sex", "age", "race", "tissue", "time", "status", gene)]

  #survplotdata <- scaled_data[,c('time', 'status', gene)]
  #colnames(survplotdata) <- c('time', 'status', gene_symbol)

  # set Z-scale cut-offs for high and low expression
  #highExpr <- 1.0
  #lowExpr <- -0.5
  #survplotdata[[gene_symbol]] <- ifelse(survplotdata[[gene_symbol]] >= highExpr, 'High',
  #                        ifelse(survplotdata[[gene_symbol]] <= lowExpr, 'Low', 'Mid'))
  # relevel the factors to have mid as the ref level
  #survplotdata[[gene_symbol]] <- factor(survplotdata[[gene_symbol]] ,
  #                         levels = c('Mid', 'Low', 'High'))
  
  # different approach
  cox.g1[[gene_symbol]] <- xtile(cox.g1[[gene]], 3)

  return(cox.g1)
}

survplotdata <- km.gene.obj(
  cox_data=cox_data,
  scaled_data=scaled_data,
  gene="ENSG00000067048", 
  gene_symbol = "DDX3Y")

p <- ggsurvplot(
  survfit(Surv(time, status) ~ DDX3Y, data = survplotdata),
  data = survplotdata,
  risk.table = TRUE,
  pval = FALSE,
  break.time.by = 500,
  ggtheme = theme_minimal(),
  risk.table.y.text.col = TRUE,
  risk.table.y.text = FALSE)

fn <- sprintf(paste(dir.figures, "kaplan_maier_DDX3Y.pdf", sep=""))
pdf(fn, height=6, width=6)
print(p)
dev.off()

```

Mine AML (adult & pediatric cell lines).
```{r}
# Validate prognostic genes with stat. significance in AML cell lines
# For TCGA select all 

# select only genes with p.adjust (wald.test) < 0.05
sig_genes_bad <- cox_mrna[cox_mrna$cntrl_padjust < 0.05 & cox_mrna$cntrl_HR > 1, ]
sig_genes_good <- cox_mrna[cox_mrna$cntrl_padjust < 0.05 & cox_mrna$cntrl_HR < 1, ]

# Essentiality imputation
for (i in seq(nrow(depmap_19Q3$avana))){
  median.na <- median(depmap_19Q3$avana[i,], na.rm=TRUE)
  if (is.na(median.na)) { median.na <- 0 }
  depmap_19Q3$avana[i, is.na(depmap_19Q3$avana[i,])] <- median.na
}

# selct adult AML cell lines
# had to take out age ....& depmap_19Q3$meta$age > 18
aml_df <- depmap_19Q3$meta[depmap_19Q3$meta$lineage_subtype=="AML" & depmap_19Q3$meta$age < 25, ]
aml_adult <- row.names(aml_df[complete.cases(aml_df$age), ])
isel <- which(colnames(depmap_19Q3$avana) %in% aml_adult)
ava_id <- colnames(depmap_19Q3$avana[, isel])
mrna_isel <- depmap_19Q3$expression[, ava_id]

# set alpha
alpha=1/3

mrna1 <- mrna_isel > apply(mrna_isel, 1, quantile, probs = alpha,  na.rm = TRUE)
mrna2 <- mrna_isel > apply(mrna_isel, 1, quantile, probs = 1-alpha,  na.rm = TRUE)
depmap_19Q3$exprq <- mrna1 + mrna2

# select genes of interest
igsel <- depmap_19Q3$exprq[row.names(sig_genes_bad), ]
igsel <- depmap_19Q3$exprq[row.names(sig_genes_good), ]
    
# divide in low and high, perform wilcoxon
stat <- NULL
i <- 1
for (gene in row.names(sig_genes_good)){
  
  print(gene)
  ihi <- names(which((igsel[gene, ] == 2)))
  ilo <- names(which((igsel[gene, ] == 0)))
      
  if (length(ihi) > 1 & length(ilo) > 1 ){
      stat[i] <- wilcox.test(depmap_19Q3$avana[gene, ilo],
                              depmap_19Q3$avana[gene, ihi], 
                             alternative="greater")$p.value
  }
  
  i <- i + 1
}

df <- data.frame(gene=row.names(sig_genes_good), stat_wilcox=stat)

      


```

Example.
```{r}
# Tutorial from https://www.biostars.org/p/344233/

```


